# Generated by Django 3.2.8 on 2021-10-29 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_neighborhood_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='author',
        ),
    ]
