# Generated by Django 3.2.8 on 2021-10-31 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0008_auto_20211029_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email_address',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
