# Generated by Django 3.2.8 on 2021-11-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_remove_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
